name: download-data

on: 
  workflow_dispatch:
    inputs:
      s3_url:
        description: The URL of the source S3 bucket
        required: true
        default: 'https://awsdstipart2.s3.amazonaws.com/kagglecatsanddogs_3367a.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download data from S3
      run: |
        wget ${{github.event.inputs.s3_url}}
